name: Trigger Project Math

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  calculate:
    uses: intellicloud/.github/.github/workflows/calculate-fields.yml@main
    secrets: inherit
