name: Trigger Project Math

on:
  projects_v2_item:
    types:
      - edited
      - created

jobs:
  calculate:
    uses: intellicloud/.github/.github/workflows/calculate-fields.yml@main
    secrets:
      ORG_APP_ID: ${{ secrets.ORG_APP_ID }}
      ORG_APP_PRIVATE_KEY: ${{ secrets.ORG_APP_PRIVATE_KEY }}
